as.data.frame(installed.packages()[,c(3:4)])

install.packages("ggplot2")
install.packages("RODBC")
install.packages("psych")
install.packages("readr")
install.packages("data.table")
install.packages("rlist")
install.packages("caret")
install.packages("rpart.plot")
install.packages("corrplot")
install.packages("e1071")
install.packages("microbenchmark")
install.packages("randomForest")